env:
  global:
    - CC_TEST_REPORTER_ID=dee70a1e9e0c213084bb2ea6ace5d1a6f9c6c4001813859d54241e9f3d9ee963
language: ruby
rvm:
  - 2.3.0
before_install: gem install bundler -v 1.11.2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  
